image: golang:1.25.7-alpine3.23

pipelines:
  default:
    - step:
        name: validate
        script:
          - wget -O- -nv https://golangci-lint.run/install.sh | sh -s
          - go mod tidy
          - golangci-lint run
          - go test -cover ./...
          - go tool govulncheck ./...
