---
log:
    level: debug
    format: json
ollama:
    endpoint: http://192.168.0.185:11434
    # Default configuration for nomic-embed-text (context length: 2048)
    embedding:
      model: nomic-embed-text
      chunk_size: 1024
      chunk_overlap: 150
    # Default configuration for mxbai-embed-large (context length: 512)
    # embedding:
    #   model: mxbai-embed-large
    #   model: deepseek-r1:7b
    #   chunk_size: 256
    #   chunk_overlap: 30
    # embedding:
    #   model: deepseek-r1:7b
    #   chunk_size: 65536
    #   chunk_overlap: 9830
    # embedding:
    #   model: pedrovillalobos/mxbai-embed-large-no-gpu
    #   chunk_overlap: 25
    #   chunk_size: 256
    # embedding:
    #   model: qllama/bge-m3:q4_k_m
    #   chunk_size: 4096
    #   chunk_overlap: 409
    generation:
        model: llama3:8b-instruct-q4_K_M
        # model: deepseek-r1:1.5b
        # model: deepseek-r1:7b
        # model: tinyllama:latest
        cache:
          enabled: false
          similarity_threshold: 0.9
        context:
          max_documents: 5
          min_similarity_score: 0.9
          enable: false
    article_analysis:
      model: phi3:3.8b-mini-4k-instruct-q4_K_M
      # model: llama3:8b-instruct-q4_K_S
agents:
  weather:
    lat: -22.881080667670826
    lon: -43.33179723978804
    timezone: America/Sao_Paulo
telemetry:
  enabled: true
  traces:
    endpoint: "192.168.0.152:4317"
  metrics:
    endpoint: "192.168.0.152:4317"
  logs:
    endpoint: "192.168.0.152:4317"
xmpp:
  notifier:
    enabled: true
